# Generated by Django 3.2.12 on 2022-04-02 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_auto_20220321_2115'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admins.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_id', models.CharField(blank=True, editable=False, max_length=1000, null=True)),
                ('first_name', models.CharField(help_text='First Name for user', max_length=255)),
                ('last_name', models.CharField(help_text='First Name for user', max_length=255)),
                ('email', models.EmailField(help_text='Your professional email that will be linked with connect account', max_length=254)),
                ('phone', models.CharField(help_text='Phone number that will be linked with connect account', max_length=15)),
                ('postal_code', models.TextField(blank=True, help_text='Postal code according to your country', null=True)),
                ('address', models.TextField(blank=True, help_text='Your home or office address.', null=True)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('business_type', models.CharField(choices=[('individual', 'individual'), ('company', 'company')], default='individual', max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, help_text='Select your city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.city')),
                ('country', models.ForeignKey(help_text='Select the country in which you reside now, according to your according payments methods, wallets and bank accounts will be visible', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.stripeacceptedcountry')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stripe Customer',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExternalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Select Bank/Card Country Name', max_length=255)),
                ('currency', models.CharField(help_text='Select Currency', max_length=255)),
                ('account_holder_name', models.CharField(help_text='Your full name on card or bank account', max_length=255)),
                ('account_holder_type', models.CharField(choices=[('individual', 'individual'), ('company', 'company')], default='individual', max_length=255)),
                ('routing_number', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=255)),
                ('connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.connect')),
            ],
            options={
                'verbose_name_plural': 'External Account',
            },
        ),
        migrations.RemoveField(
            model_name='stripeaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
        migrations.DeleteModel(
            name='StripePaymentMethod',
        ),
        migrations.DeleteModel(
            name='StripeAccount',
        ),
        migrations.DeleteModel(
            name='StripeCustomer',
        ),
    ]
