# Generated by Django 3.2.12 on 2022-03-24 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='address',
            field=models.TextField(blank=True, help_text='Your home or office address.', null=True),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='country',
            field=models.ForeignKey(help_text='Select the country in which you reside now, according to your according payments methods, wallets and bank accounts will be visible', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.stripeacceptedcountry'),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='name',
            field=models.CharField(help_text='Kindly! use your full correct name that must be same to your National ID, Passport or Bank Acounts', max_length=255),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='phone',
            field=models.CharField(help_text='Phone number without country code', max_length=15),
        ),
        migrations.AlterField(
            model_name='stripecustomer',
            name='postal_code',
            field=models.TextField(blank=True, help_text='Postal code according to your country', null=True),
        ),
    ]
