# Generated by Django 3.2.12 on 2022-04-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20220402_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='business_type',
            field=models.CharField(choices=[('individual', 'individual')], default='individual', max_length=255),
        ),
        migrations.AlterField(
            model_name='connect',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Postal code according to your country and city', max_length=255, null=True),
        ),
    ]
