# Generated by Django 3.2.12 on 2022-04-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20220402_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccount',
            name='connect',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.connect'),
        ),
    ]
