# Generated by Django 3.2.12 on 2022-04-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_externalaccount_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccount',
            name='account_holder_type',
            field=models.CharField(choices=[('individual', 'individual')], default='individual', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='country',
            field=models.ForeignKey(help_text='Select Bank/Card Country Name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.stripeacceptedcountry'),
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='currency',
            field=models.ForeignKey(help_text='Select Currency according to your account', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.currency'),
        ),
    ]
