# Generated by Django 3.2.12 on 2022-04-03 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20220403_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccount',
            name='connect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.connect'),
        ),
    ]
