# Generated by Django 3.2.12 on 2022-04-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_externalaccount_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='account_type',
            field=models.CharField(choices=[('card', 'Card'), ('bank', 'Bank')], default='bank', max_length=255),
        ),
    ]
