# Generated by Django 3.2.12 on 2022-04-03 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_externalaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='short_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
