# Generated by Django 3.2.12 on 2022-04-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_auto_20220403_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccount',
            name='external_account_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
