# Generated by Django 3.2.12 on 2022-04-07 15:17

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_externalaccount_external_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='last_name',
            field=models.CharField(help_text='Last Name for user', max_length=255),
        ),
        migrations.AlterField(
            model_name='connect',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number that will be linked with connect account', max_length=128, region=None),
        ),
    ]
