# Generated by Django 3.2.12 on 2022-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20220407_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='address',
            field=models.CharField(blank=True, help_text='Your home or office address.', max_length=1000, null=True),
        ),
    ]
