# Generated by Django 3.2.12 on 2022-04-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_alter_connect_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='email',
            field=models.EmailField(blank=True, help_text='Your professional email that will be linked with connect account', max_length=254),
        ),
        migrations.AlterField(
            model_name='connect',
            name='first_name',
            field=models.CharField(blank=True, help_text='First Name for user', max_length=255),
        ),
        migrations.AlterField(
            model_name='connect',
            name='last_name',
            field=models.CharField(blank=True, help_text='Last Name for user', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='account_number',
            field=models.CharField(help_text="Use '00012345' for testing purpose", max_length=255),
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='routing_number',
            field=models.CharField(help_text="Use '108800' for testing purpose", max_length=255),
        ),
    ]
