# Generated by Django 3.2.12 on 2022-04-14 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20220414_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='dollar', max_length=100),
        ),
        migrations.AlterField(
            model_name='externalaccount',
            name='routing_number',
            field=models.CharField(help_text="Use '108800' for testing purpose -- SortCode for UK and Routing Number for US customers", max_length=255, verbose_name='RoutingNumber/SortCode'),
        ),
    ]
