# Generated by Django 3.2.12 on 2022-04-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20220414_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.currency'),
        ),
    ]
