# Generated by Django 3.2.9 on 2022-02-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_auto_20220224_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topup',
            old_name='amount',
            new_name='received',
        ),
        migrations.AddField(
            model_name='topup',
            name='tax',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topup',
            name='total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
