# Generated by Django 3.2.9 on 2022-02-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_auto_20220224_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='payment_method',
            field=models.CharField(choices=[('str', 'Stripe')], default='str', max_length=3),
        ),
    ]
