# Generated by Django 3.2.9 on 2022-02-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_withdrawal_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='topup',
            name='payment_method',
            field=models.CharField(choices=[('str', 'Stripe')], default='str', max_length=3),
        ),
    ]
