# Generated by Django 3.2.9 on 2022-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_auto_20220224_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='topup',
            name='stripe_payment_intent',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
