# Generated by Django 3.2.9 on 2022-02-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_topup_stripe_payment_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='stripe_payment_intent',
            field=models.CharField(max_length=20000),
        ),
    ]
