# Generated by Django 3.2.9 on 2022-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_alter_topup_stripe_payment_intent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='bank_account_number',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
