# Generated by Django 3.2.9 on 2022-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_auto_20220224_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='amount',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='received',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account_holder_name',
            field=models.CharField(blank=True, help_text="If current user is not account holder then please place bank account holder's name to avoid payment block.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(help_text='Account Number or IBAN Number', max_length=1000),
        ),
    ]
