# Generated by Django 3.2.9 on 2022-02-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_auto_20220224_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='total',
            field=models.FloatField(verbose_name='Amount'),
        ),
    ]
