# Generated by Django 3.2.10 on 2022-03-01 23:57

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_auto_20220302_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of image must be 100*100 and format must be png image file', keep_meta=True, null=True, quality=75, size=[100, 100], upload_to='accounts/images/profiles/'),
        ),
    ]
