# Generated by Django 3.2.12 on 2022-04-02 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_auto_20220321_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
