# Generated by Django 3.2.12 on 2022-04-05 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_externalaccount_external_account_id'),
        ('admins', '0017_auto_20220402_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='country',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='connected_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.externalaccount'),
        ),
    ]
