# Generated by Django 3.2.9 on 2022-02-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_student',
            new_name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
    ]
