# Generated by Django 3.2.9 on 2022-02-23 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220223_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='top_up_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction_limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='wallet',
            name='withdrawal_limit',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
