# Generated by Django 3.2.9 on 2022-02-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220223_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_top_up',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_top_up_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_transactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_transactions_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_withdrawal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_withdrawal_amount',
            field=models.FloatField(default=0),
        ),
    ]
