# Generated by Django 3.2.9 on 2022-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220223_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='total_transactions_amount',
            new_name='total_transactions_amount_received',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='total_transactions',
            new_name='total_transactions_received',
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_transactions_amount_sent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_transactions_sent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
