# Generated by Django 3.2.10 on 2022-03-01 22:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', help_text='size of logo must be 100*100 and format must be png image file', keep_meta=True, null=True, quality=75, size=[200, 200], upload_to='accounts/images/profiles/'),
        ),
    ]
