# Generated by Django 3.2.10 on 2022-03-04 11:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='code',
            new_name='qr_code',
        ),
        migrations.AddField(
            model_name='wallet',
            name='qr_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='size of logo must be 200*200 and format must be png image file', keep_meta=True, null=True, quality=75, size=[1920, 1080], upload_to='account/images/wallets/'),
        ),
    ]
