# Generated by Django 3.2.10 on 2022-03-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usersanction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='usersanction',
            options={'ordering': ['-user'], 'verbose_name_plural': 'User Sanctions'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-user'], 'verbose_name_plural': 'Wallets'},
        ),
    ]
