# Generated by Django 3.2.12 on 2022-03-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_stripeaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripeAccount',
        ),
    ]
