# Generated by Django 3.2.12 on 2022-04-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_stripeaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='connect_amount',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
