# Generated by Django 3.2.12 on 2022-04-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_wallet_connect_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='connect_amount',
            field=models.FloatField(default=0),
        ),
    ]
